const travelDetails = [
    {
      id: 1,
      fullName: 'Dia Leocadio',
      destination: 'Star City',
      package: 'Basic',
      travelDate: 'March 2 2023',
      status: 'Waitlist',
      cancelledReason: '',
      transportationCost: 1100,
      accommodationCost: 3000,
      otherCost: 1100,
      totalCost: 5200
    },
    {
      id: 2,
      fullName: 'Elnie Ebasan',
      destination: 'Mt. Apo',
      package: 'Premium',
      travelDate: 'March 3 2023',
      status: 'Waitlist',
      cancelledReason: '',
      transportationCost: 1400,
      accommodationCost: 2900,
      otherCost: 1000,
      totalCost: 5300
    },
    {
      id: 3,
      fullName: 'Faith Mariano',
      destination: 'Calle Crisologo',
      package: 'Standard',
      travelDate: 'March 4 2023',
      status: 'Waitlist',
      cancelledReason: '',
      transportationCost: 1300,
      accommodationCost: 2800,
      otherCost: 900,
      totalCost: 5000
    },
    {
      id: 4,
      fullName: 'Gene Espejo',
      destination: 'Chocolate Hills',
      package: 'Basic',
      travelDate: 'March 5 2023',
      status: 'Waitlist',
      cancelledReason: '',
      transportationCost: 1200,
      accommodationCost: 2700,
      otherCost: 800,
      totalCost: 4700
    },
    {
      id: 5,
      fullName: 'James Osias',
      destination: 'Rizal Park',
      package: 'Premium',
      travelDate: 'March 6 2023',
      status: 'Confirmed',
      cancelledReason: '',
      transportationCost: 1700,
      accommodationCost: 2600,
      otherCost: 700,
      totalCost: 5000
    },
    {
      id: 6,
      fullName: 'Joffrey Acula',
      destination: 'Fort Santaiago',
      package: 'Standard',
      travelDate: 'March 7 2023',
      status: 'Confirmed',
      cancelledReason: '',
      transportationCost: 1600,
      accommodationCost: 2500,
      otherCost: 600,
      totalCost: 4700
    },
    {
      id: 7,
      fullName: 'Rendi Aguila',
      destination: 'Mt .Apo',
      package: 'Basic',
      travelDate: 'March 8 2023',
      status: 'Cancelled',
      cancelledReason: 'Lorem ipsum dolor sit amet.',
      transportationCost: 1500,
      accommodationCost: 2400,
      otherCost: 500,
      totalCost: 4400
    },
    {
      id: 8,
      fullName: 'Mohn Javier',
      destination: 'Fort Santiago',
      package: 'Premium',
      travelDate: 'March 9 2023',
      status: 'Waitlist',
      cancelledReason: '',
      transportationCost: 2000,
      accommodationCost: 2300,
      otherCost: 400,
      totalCost: 4700
    },
    {
      id: 9,
      fullName: 'Ram Libres',
      destination: 'Rizal Shrine',
      package: 'Standard',
      travelDate: 'March 10 2023',
      status: 'Cancelled',
      cancelledReason: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, amet.',
      transportationCost: 1900,
      accommodationCost: 2200,
      otherCost: 300,
      totalCost: 4400
    },
    {
      id: 10,
      fullName: 'Sketch Caneba',
      destination: 'Chinatown',
      package: 'Basic',
      travelDate: 'March 12 2023',
      status: 'Tentative',
      cancelledReason: '',
      transportationCost: 1800,
      accommodationCost: 2100,
      otherCost: 200,
      totalCost: 4100
    }
  ]

export default travelDetails;